### PR TITLE
Test in PHP 8

### PR DESCRIPTION
**Pull request by donatj**

### CODE REVIEW

**Comment by peter279k** [comment]
The tests are failed because the PHPUnit running is problematic.

Ti fix above issue, it should define more PHPUnit versions on `composer.json` file to be compatible with different PHP versions.

For example, it can be `phpunit/phpunit: "^4.8.36 || ^5.7 || ^6.5 || ^7.0 || ^8.0 || ^9.0"`.

**Comment by donatj** [comment]
@peter279k I poked this much more throughly elsewhere. Even the newest tagged version of PHPUnit for PHP 8.0 does not work without turning off platform requirements because the phpspec/prophecy ( see: https://github.com/phpspec/prophecy/blob/b20034be5efcdab4fb60ca3a29cba2949aead160/composer.json#L21 ) dependency has not been updated for 8 yet. Other may not have either, that’s just where composer died.

**Comment by peter279k** [comment]
> 
> 
> @peter279k I poked this much more throughly elsewhere. Even the newest tagged version of PHPUnit for PHP 8.0 does not work without turning off platform requirements because the phpspec/prophecy ( see: https://github.com/phpspec/prophecy/blob/b20034be5efcdab4fb60ca3a29cba2949aead160/composer.json#L21 ) dependency has not been updated for 8 yet. Other may not have either, that’s just where composer died.

Yes. We should add the `--ignore-platform-reqs` to let `composer install` command be worked/successful.

And I also suggest that the PHPUnit versions should be considered, too. The log is available [here](https://github.com/donatj/PhpUserAgent/pull/66/checks?check_run_id=1057131976).

**Comment by donatj** [comment]
Turning on `--ignore-platform-reqs` just adds uncertainty to the test environment. 

I'm going to just wait for PHPUnit to be stable and functional on PHP 8 before I enable testing on 8.

**Pull request merged**
