### PR TITLE
Fix passing null to string parameter deprecation

### PR DESCRIPTION
**Pull request by kocsismate**
Fixing `strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated`

### CODE REVIEW

**Comment by donatj** [comment]
Do you have a particular UA string that triggers the issue?

**Comment by kocsismate** [comment]
> D

Yes, our test suite contains a `Lenovo-A880/S100 Linux/3.4.5 Android/4.2 Release/08.07.2013 Browser/AppleWebKit 534.30 Profile/ Configuration;` `User-Agent` value which triggers it.

**Comment by donatj** [comment]
Thanks! I just wanted to potentially add a regression test. PHP 8.1 is really snippy about strings.

**Comment by kocsismate** [comment]
I added a test. Can you please approve the workflow so that CI can be started?

**Comment by donatj** [comment]
This was manually merged as part of a35900b93530715f8669c10e49756adde5c8e6fc

It has been tagged and released in https://github.com/donatj/PhpUserAgent/releases/tag/v1.7.0

Thanks again!

**Comment by kocsismate** [comment]
Thank you for your quick help!

**Pull request closed without merging**
