### PR TITLE
add support for PSP browser

### PR DESCRIPTION
**Pull request by Znerole**
Added detection of NetFront 2.0 browser on PSP (see here: http://www.useragentstring.com/Playstation%20Portable2.00_id_6496.php).

### CODE REVIEW

**Comment by donatj** [comment]
Very nice pull request including test updates. 

Is ***anyone*** still using the PSP browser? Are there any statistics on this?  Is this something you specifically need to detect?

There are a lot of dead browsers I *could* add support for, such as my personal favorite NetPositive for BeOS, but if the test for it will never ever be hit again, it's just wasted CPU time.

**Comment by Znerole** [comment]
I guess not. The PSP was just a test device I found to throw at a website I'm moving to HTML5. I understand your rationale (no dead browsers), so you should not merge this.

Maybe someday for a zombie edition, together with your BeOS browser and Mosaic.  ;)

On 16 February 2016 00:51:56 CET, Jesse Donat <notifications@github.com> wrote:
>Very nice pull request including test updates. 
>
>Is ***anyone*** still using the PSP browser? Are there any statistics
>on this?  Is this something you specifically need to detect?
>
>There are a lot of dead browsers I *could* add support for, such as my
>personal favorite NetPositive for BeOS, but if the test for it will
>never ever be hit again, it's just wasted CPU time.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/donatj/PhpUserAgent/pull/35#issuecomment-184445061

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by donatj** [comment]
I truly appreciate the pull request and am on the fence - but… I think I'm going to close it I'm afraid.

**Comment by Znerole** [comment]
No harm done!

**Pull request closed without merging**
