### PR TITLE
Added detect mobile browsers: Firefox, Yandex, UC Browser for iPhone/Android and Vienna RSS reader

### PR DESCRIPTION
**Pull request by landy2005**

### CODE REVIEW

**Comment by donatj** [comment]
Hah, I knew adding CriOS was a mistake. now I've opened the flood gate to all these Safari Wrapper non-browsers.

**Comment by landy2005** [comment]
Heh, but what to do if they really are. And it's not their fault that Apple does not allow to use its own engines.

**Comment by donatj** [comment]
I've gotta think about this. You could try to convince me this is a good idea :smirk:

**Comment by landy2005** [comment]
I don't want convince to you. It's just a fact that this Firefox/Yandex/etc browsers (not a Chrome or Safari as detected before).

If you make a more elegant way to determine their, this will be good.

**Comment by donatj** [comment]
I merged UC Browser here: 552273da22a5a1a0ca5b68e0bbe10680c26ca3e9 because they're at 7% globally according to what I was reading, after which I did some fairly major refactoring you may want to look at for your fork. -18 loc

I'm leaveing this open for the time being as a reminder to myself about the other browsers I'm currently ignoring exist ;)

**Comment by donatj** [comment]
Closing because it is a year old and no longer cleanly applies. If you're still interested you can reopen later without the merge issues.

**Pull request closed without merging**
