### PR TITLE
Remove anonymous function call

### PR DESCRIPTION
**Pull request by toolstack**
I have several user's getting error messages from PHP 5.4 about the anonymous function call for the $find function.  Some users are using eAccelerator (which is broken and a dead project) some say they are not.

As it's not really required and in fact adds overhead, this change removes it's use.

This change also removes the strtolower() call for the search term (it's always a hard coded string so I just manually lowered the strings) and only calls strtolower() once for the results array (instead of on each call to $find).

### CODE REVIEW

**Comment by donatj** [comment]
The status of the unit tests is currently failing, if you notice the Travis warning on this pull request. If you can get them passing I'll consider the changes.

**Comment by toolstack** [comment]
Ok, I've fixed all the unit tests, though it looks like Travis just dedicated to take a nap after my last commit so it's reporting failed PHP:hhvm test due to a timeout downloading the dependencies.

**Comment by donatj** [comment]
Give a look now at the new Scrutinizer issues if you would be so kind

**Comment by toolstack** [comment]
I took a look at the Scrutinizer issues, but all three seem to be false positives. 

I did make another small change to catch a corner case.

Also there is a bug in the original code I fixed, in the AppleWebKit if the following line:

`if( ($platform == 'Android' && !($key = 0)) ) {`

uses an assignment operator instead of a comparison operator for $key.

**Comment by toolstack** [comment]
And of course the "fix" above has broken one of the tests, if I had to guess I'd say the whole first if case should be remove as it was never executed before.

**Comment by toolstack** [comment]
Travis is reporting that PHP:hhvm test failed again due to a timeout downloading the dependencies, but everything else is passing now.

**Comment by donatj** [comment]
Can you try pulling in .travis.yml from master? I pushed a small change.

**Comment by toolstack** [comment]
Done.

**Comment by toolstack** [comment]
Anything else?

**Comment by donatj** [comment]
I've been very very busy with work on an impending major release, it may be a bit before I can properly review the code.

**Comment by toolstack** [comment]
No problem, thanks.

**Comment by toolstack** [comment]
Any idea when you'll get a chance to look at this?

**Comment by donatj** [comment]
It muddles up the code a ton for very little gain. 

It's a 10% increase in code to help support people with bad PHP setups. I'm having trouble justifying it.

**Comment by donatj** [comment]
That said, I'm still mulling it over.

**Comment by toolstack** [comment]
Ok, I've had several more reports of the existing code failing so I've got to do something about it.  

Let me know what you decide, thanks.

**Comment by donatj** [comment]
eAccelerator is dead, as attested to [here](https://github.com/eaccelerator/eaccelerator/pull/44). The last update was in [August 2012](https://github.com/eaccelerator/eaccelerator/commits/master). 

I feel like supporting it isn't prudent or worth my time. It's probably not worth yours either. 

If you wish to support them I suggest maintaining a fork yourself.

**Comment by toolstack** [comment]
Not looking to support eAccelerator and I have several users with plain vanilla 5.4 installs who had the issue as well. 

The changes does several things, better performance and memory usage (removes one level of function nesting) and makes the code more readable.  It just so happens to solve the other issue as well ;)

**Pull request closed without merging**
